# -*- coding: utf-8 -*-
"""
Complete standalone repository generation.

Turns a single shielded source file into a turn-key, idiomatic Rust/pyo3 project
folder that can be pushed straight to GitHub:

* ``Cargo.toml``      -- inferred metadata + dependencies (``rug``, ``pyo3``),
  with ``crate-type = ["cdylib"]`` for a Python extension module;
* ``src/lib.rs``      -- the corrected, shielded source;
* ``.gitignore``      -- ignores ``target/`` and compiled artefacts;
* ``README.md``       -- basic build/use instructions;
* ``test_binding.py`` -- a quick Python import/verification check-script.

The manifest is rendered by the existing :mod:`src.build.cargo_manifest` emitter
so there is a single source of truth for TOML formatting.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.build.cargo_manifest import render_manifest, sanitize_crate_name

# Conservative, modern default versions for the anchored crates.
_DEFAULT_DEPENDENCY_VERSIONS = {
    "rug": "1.24",
    "pyo3": {"version": "0.22", "features": ["extension-module"]},
}


@dataclass
class RepoSpec:
    """Everything needed to materialise a standalone crate."""

    name: str
    source: str  # shielded lib.rs contents
    version: str = "0.1.0"
    edition: str = "2021"
    description: str = ""
    dependencies: Dict[str, Any] = field(default_factory=dict)
    crate_type: List[str] = field(default_factory=lambda: ["cdylib"])
    python_module: Optional[str] = None  # the #[pymodule] name, if any

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "edition": self.edition,
            "description": self.description,
            "dependencies": dict(self.dependencies),
            "crate_type": list(self.crate_type),
            "python_module": self.python_module,
        }


@dataclass
class GeneratedRepo:
    """The files written for a standalone repo."""

    root: Path
    files: List[str] = field(default_factory=list)
    spec: Optional[RepoSpec] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "root": str(self.root),
            "files": list(self.files),
            "spec": self.spec.to_dict() if self.spec else None,
        }


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------


def infer_dependencies(source: str, overrides: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Infer crate dependencies from a Rust source, applying any overrides."""
    deps: Dict[str, Any] = {}
    for crate, default in _DEFAULT_DEPENDENCY_VERSIONS.items():
        if re.search(rf"\b(?:use|extern crate)\s+{crate}\b", source) or re.search(rf"\b{crate}::", source):
            deps[crate] = default
    if overrides:
        deps.update(overrides)
    return deps


def detect_pymodule(source: str) -> Optional[str]:
    """Find the ``#[pymodule]`` function name, if the source defines one."""
    match = re.search(r"#\[pymodule\][^\n]*\n\s*(?:pub\s+)?fn\s+([A-Za-z_]\w*)", source)
    if match:
        return match.group(1)
    # Some sources use `#[pymodule] fn name(...)` on one line.
    match = re.search(r"#\[pymodule\]\s*(?:pub\s+)?fn\s+([A-Za-z_]\w*)", source)
    return match.group(1) if match else None


def build_spec(
    name: str,
    source: str,
    dependencies: Optional[Dict[str, Any]] = None,
    description: str = "",
) -> RepoSpec:
    """Assemble a :class:`RepoSpec` from a name + shielded source."""
    crate_name = sanitize_crate_name(name)
    deps = infer_dependencies(source, dependencies)
    pymodule = detect_pymodule(source)
    # A pyo3 extension module is a cdylib; a plain rug crate is a normal lib.
    crate_type = ["cdylib"] if "pyo3" in deps else ["rlib"]
    return RepoSpec(
        name=crate_name,
        source=source,
        description=description or f"Standalone crate generated by Aero Universal for '{crate_name}'.",
        dependencies=deps,
        crate_type=crate_type,
        python_module=pymodule,
    )


# ---------------------------------------------------------------------------
# File templates
# ---------------------------------------------------------------------------


def render_gitignore() -> str:
    return (
        "# Rust build output\n"
        "/target/\n"
        "build_artifacts/\n"
        "**/*.rs.bk\n"
        "Cargo.lock\n\n"
        "# Compiled Python extension artefacts\n"
        "*.so\n"
        "*.pyd\n"
        "*.dylib\n"
        "__pycache__/\n"
        "*.py[cod]\n"
    )


def render_readme(spec: RepoSpec) -> str:
    deps = ", ".join(f"`{name}`" for name in spec.dependencies) or "(none)"
    module = spec.python_module or spec.name
    lines = [
        f"# {spec.name}",
        "",
        spec.description,
        "",
        "> Generated by **Aero Universal** as a standalone, turn-key repository.",
        "",
        "## Dependencies",
        "",
        f"Crates: {deps}",
        "",
        "## Build",
        "",
        "```bash",
        "# Build the native library / Python extension module",
        "cargo build --release",
        "```",
        "",
        "## Use from Python",
        "",
        "```bash",
        "pip install maturin   # or use cargo + a manual copy of the .so",
        "maturin develop --release",
        f"python -c \"import {module}; print({module})\"",
        "```",
        "",
        "## Verify",
        "",
        "```bash",
        "python test_binding.py",
        "```",
        "",
    ]
    return "\n".join(lines)


def render_test_binding(spec: RepoSpec) -> str:
    module = spec.python_module or spec.name
    return (
        '"""Quick verification that the compiled extension imports and loads.\n\n'
        "Generated by Aero Universal.  Build the module first (e.g. `maturin develop`\n"
        "or `cargo build --release` + copy the .so onto the Python path).\n"
        '"""\n\n'
        "import importlib\n"
        "import sys\n\n"
        f'MODULE = "{module}"\n\n\n'
        "def main() -> int:\n"
        "    try:\n"
        "        mod = importlib.import_module(MODULE)\n"
        "    except ImportError as exc:\n"
        '        print(f"[FAIL] could not import {MODULE!r}: {exc}")\n'
        '        print("       build it first: `cargo build --release` / `maturin develop`")\n'
        "        return 1\n"
        f'    print(f"[ OK ] imported {{MODULE!r}} -> {{mod!r}}")\n'
        "    print(\"       exported attributes:\", [a for a in dir(mod) if not a.startswith(\"_\")])\n"
        "    return 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    sys.exit(main())\n"
    )


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def generate_repo(spec: RepoSpec, dest_dir: Path) -> GeneratedRepo:
    """Write the full standalone project layout under ``dest_dir``."""
    root = Path(dest_dir)
    src_dir = root / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    manifest = render_manifest(
        crate_name=spec.name,
        dependencies=spec.dependencies,
        edition=spec.edition,
        version=spec.version,
        crate_type=spec.crate_type,
        header=f"{spec.name} — standalone crate generated by Aero Universal.",
    )

    written: List[str] = []

    def _write(relative: str, content: str) -> None:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(relative)

    _write("Cargo.toml", manifest)
    _write("src/lib.rs", spec.source if spec.source.endswith("\n") else spec.source + "\n")
    _write(".gitignore", render_gitignore())
    _write("README.md", render_readme(spec))
    _write("test_binding.py", render_test_binding(spec))

    return GeneratedRepo(root=root, files=written, spec=spec)
